### ISSUE TITLE
Compare decentralized and centralized search of items

### ISSUE THREAD

**Issue by kabirkbr** [singnet/offernet#15]
The general issue of decentralization vs centralization is explained [here](https://singnet.github.io/offernet/public/offernet-documentation/conceptual-framework.html#centralization-decentralization). Shortly, we need to figure out what are the circumstances when decentralized search (and processing in general) is more efficient / makes more sense than centralized.

See [description of experiment](https://singnet.github.io/offernet/public/offernet-documentation/implementation.html#compare-decentralized-and-centralized-search).

Subtasks:
- [x] #35 finish decentralizedSearch routine;
- [x] #36 finish centralizedSearch routine;
- [x] #37 benchmark search routines and build report;
- [x] #50 interpretation and conceptual analysis of the 'decentralized vs centralized' experiment
- [x] #55 Run more experiments for showing success on random graph dependency on maxDistance parameter
- [x] #57 Incorrect calculation of centralized simulations running times;
- [ ] #58 Incorrect calculation of decentralized simulations total running time;

**Comment by kabirkbr** [comment]
Closed with #53

**Comment by kabirkbr** [comment]
Reopened due to the issues #55 and #57.
